import sys
import spotipy
import spotipy.util as util

scope = 'playlist-modify-private'

if len(sys.argv) > 1:
    username = sys.argv[1]
else:
    print "Usage: %s username" % (sys.argv[0],)
    sys.exit()

token = util.prompt_for_user_token(username, scope)

if token:
    s = spotipy.Spotify(auth=token)
    user_id = s.me().get("id")

    s.user_playlist_create(user_id, 'test',False, description='Generated by sbotify')

else:
    print "Failed to get token for", username
